### ISSUE TITLE
Project maintenance status

### ISSUE THREAD

**Issue by timhilliard** [oriordan/yubistack#3]
Hi there,

Was wondering what the status of this project is? Is it still maintained? Are you open to new collaborators or transfer of project?

I'm trying to avoid forking so just wanted to see what maintenance looks like on this project first?

Thanks,
Tim

**Comment by oriordan** [comment]
Hi Tim,

Sorry I did not see this earlier. This project is not maintained anymore, so feel free to take it over if you're interested.
Any approach works for me.

Cheers!

**Comment by timhilliard** [comment]
To add me as a collaborator you will need to add me in the settings of the project. I would also need you to add me in the project in pypi.

**Comment by oriordan** [comment]
Done
